[package]
name = "decoder"
version = "0.1.0"
authors = ["you <you@example.com>"]
edition = "2021"

[lib]
name = "decoder"
path = "src/lib.rs"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
bs58 = "0.5"

